// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAFDf-LBD626Q0_8NEpA-f8gtrMWTPU5Q',
    appId: '1:8261873530:web:f3b74cab897179377ef0c3',
    messagingSenderId: '8261873530',
    projectId: 'flutter-management-gbl',
    authDomain: 'flutter-management-gbl.firebaseapp.com',
    storageBucket: 'flutter-management-gbl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ygZnVSz39FzAPZaZAGvmd7gdVXf3lms',
    appId: '1:8261873530:android:8ca204584a4827937ef0c3',
    messagingSenderId: '8261873530',
    projectId: 'flutter-management-gbl',
    storageBucket: 'flutter-management-gbl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKY5k1RvuQKitwUhH1SKaOyWYTyq4Rec',
    appId: '1:8261873530:ios:23c45c320148238c7ef0c3',
    messagingSenderId: '8261873530',
    projectId: 'flutter-management-gbl',
    storageBucket: 'flutter-management-gbl.appspot.com',
    iosClientId: '8261873530-up01gdusnbv56h0lj7u7n6e5lnadpg5i.apps.googleusercontent.com',
    iosBundleId: 'yes',
  );
}
